/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class radenko_mihajlovic_smarthospital_JNIExample */

#ifndef _Included_radenko_mihajlovic_smarthospital_JNIExample
#define _Included_radenko_mihajlovic_smarthospital_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     radenko_mihajlovic_smarthospital_JNIExample
 * Method:    hashPassword
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_radenko_mihajlovic_smarthospital_JNIExample_hashPassword
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     radenko_mihajlovic_smarthospital_JNIExample
 * Method:    unhashPassword
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_radenko_mihajlovic_smarthospital_JNIExample_unhashPassword
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
